---
title: "STA243 Hw4"
author:
- Eric Kalosa-Kenyon
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: This assignment enforces Monte Carlo methods and exhibits MCMCs.
output:
  html_document:
    toc: yes
---


# 1
## 1.a
$$\int_0^1 x^2 dx$$
We use $f(x)=x^2$ and $p(x)=1$ uniform over the $[0,1]$ interval.

```{r}
### R version 3.3.2 (2016-10-31) "Sincere Pumpkin Patch"
# x86_64-apple-darwin15.6.0 svn rev 71607

### BEGIN: Code

## Preamble
rm(list=ls())
set.seed(10)

## Imports
library(ggplot2)
library(latex2exp)

## Subroutines
f = function(x){
    return(x^2)
}
p = function(x){
    return(1)
}
f = Vectorize(f)
p = Vectorize(p)

## Parameterize
N = 5000 # Upper limit of samples to average for the MC integral estimation
m = 50 # Sample N/m, 2N/m, .., N times to observe convergence rate
K = 10000 # Resolution on the interval over which to sample w.r.t p(x)
v = 1 # int_0^1 dx = 1

## Simulate
pxs = seq(0, 1, length.out=K)
i1s = rep(NA, m)
ns = (1:m)*N/m
for(i in 1:m){ # m is small so this is fast enough
    xs = sample(pxs, ns[i], prob=p(pxs), replace=T) # sample according to p(x)
    i1 = v*mean(f(xs)) # sample mean of f(x)
    i1s[i] = i1
}

## Plot
df_plt1 = data.frame(x = ns, y = i1s)
plt1 = ggplot(data=df_plt1, aes(x=x, y=y)) +
    geom_line() +
    geom_hline(yintercept = 1/3) + # true evaluation
    labs(
         x="Samples",
         y="MC Estimation",
         title=latex2exp("MC Estimation of \\int_0^1 x^2 dx")
         )
plt1

### END: Code
```

The Monte Carlo estimation of $\int_0^1 x^2 dx$ is $\hat{I}=`r i1`$.
The exact evaluation is $I=\frac{x^3}{3}\bigg\rvert_0^1 = \frac{1}{3}$.
We are off by $\mid I-\hat{I}\mid=`r abs(i1-1/3)`$ which is only a factor of
$\frac{\mid I-\hat{I}\mid}{1/3}=`r abs(i1-1/3)/(1/3)`$.

## 1.b

$$\int_{-2}^2 \int_0^1 x^2 \cos(xy) dxdy$$
We use $f(x,y)=x^2\cos(xy)$ and $p(x,y)=\frac{1}{4}$ uniform over the
$[0,1]\times[-2,2]$ domain.

```{r}
### BEGIN: Code

## Subroutines
f = function(x, y){
    return(x^2*cos(x*y))
}
f = Vectorize(f)

## Parameterize
N = 5000 # Upper limit of samples to average for the MC integral estimation
m = 50 # Sample N/m, 2N/m, .., N times to observe convergence rate
Kx = 1000 # Resolution on the interval over which to sample w.r.t p(x)
Ky = 2000
v = 4 # int_0^1 int_-2^2 dxdy

## Simulate
pxs = seq(0, 1, length.out=Kx)
pys = seq(-2, 2, length.out=Ky)
i2s = rep(NA, m)
ns = (1:m)*N/m
for(i in 1:m){ # m is small so this is fast enough
    xs = sample(pxs, ns[i], replace=T) # sample uniformly
    ys = sample(pys, ns[i], replace=T)
    i2 = v*mean(f(xs, ys)) # sample mean of f(x)
    i2s[i] = i2
}

## Plot
tru = 1/2*(sin(2)-2*cos(2))
df_plt2 = data.frame(x = ns, y = i2s)
plt2 = ggplot(data=df_plt2, aes(x=x, y=y)) +
    geom_line() +
    geom_hline(yintercept = tru) + # true evaluation
    labs(
         x="Samples",
         y="MC Estimation",
         title=latex2exp(paste(
            "MC Estimation of",
            "\\int_{-2}^2\\int_0^1 x^2 cos(xy) dxdy"
            ))
         )
plt2

### END: Code
```
