---
title: "STA243 Hw1 - Eric Kalosa-Kenyon"
output:
  html_document:
    toc: yes
---

```{r, message=F, warning=F}
library("ggplot2")          # fancy plotting
```

# 1
## 1.a
$p_n(x_1\dots x_n, \theta) = \prod_{i=1}^{n} p(x_i, \theta)$ where
$p(x, \theta) = \frac{1}{\pi*(1+(x-\theta)^2)}$. Hence,
$l_n(\theta) = \log{p_n(x_1\dots x_n, \theta)} =
    -n\log{\pi}-\sum_{i=1}^{n}{\log{1+(x_i-\theta)^2}}$
  
Further, $l_n^{'}(\theta) = \frac{\partial}{\partial \theta} l_n(\theta) =
    -\sum_{i=1}^{n} \frac{\partial}{\partial \theta} \log{1+(x_i-\theta)^2} =
    -2\sum_{i=1}^{n} \frac{\theta-x_i}{1+(x_i-\theta)^2}$.
  
Finally, $foo-bar$

## 1.b
TODO

## 1.c
```{r}
# raw = c(−13.87, −2.53, −2.44, −2.40, −1.75, −1.34, −1.05, −0.23, −0.07, 0.27,
        # 1.77, 2.76, 3.29, 3.47, 3.71, 3.80, 4.24, 4.53, 43.21, 56.75)
raw = 1:4

p_1 = function(x, t){
    d = pi*(1+(x-t)^2)
    return(1/d)
}
p_n = function(xs, t){
    r = 1
    for(x in xs){
        r = r*p_1(x,t)
    }
    return(r)
}
l_n = function(xs, t){
    return(log(p_n(xs,t)))
}

ts = seq(from=min(raw), to=max(raw), length=100)
# plot(ts, p_n(xs=raw, t=ts), main="Log likelihood")
df = data.frame(ts, p_n(xs=raw, t=ts))
names(df) = c("theta", "loglik")
ggplot(df, aes(x="theta")) + geom_density()
```


# 2
```{r}
foo = 2
```
